# Aula 05 - Métodos Importantes e Máscaras em Arrays

1. Métodos Importantes
    - ndim
    - shape
    - dtype
    - astype
    - min
    - max
    - argmin
    - argmax
    - sum
    - mean
    - var
    - std
    - sort
    - T
    - reshape

2. Máscaras

In [1]:
import numpy as np

In [2]:
array = np.random.randn(10)

In [3]:
array

array([ 0.11928221,  0.96270531, -0.29978465, -0.36174703,  0.92503407,
        0.44241508, -0.61289282, -1.63363194,  0.08057173, -1.96363072])

In [4]:
mtx = np.random.randn(3, 3)

In [5]:
mtx

array([[ 0.31453409,  1.42728671,  0.0250084 ],
       [-0.15931809, -0.70811228,  0.86123226],
       [ 0.74442808,  0.41159497,  0.58874685]])

In [6]:
array.ndim

1

In [7]:
mtx.ndim

2

In [8]:
array.shape

(10,)

In [9]:
mtx.shape

(3, 3)

In [10]:
array.dtype

dtype('float64')

In [11]:
array.astype('int')

array([ 0,  0,  0,  0,  0,  0,  0, -1,  0, -1])

In [12]:
mtx.astype('int')

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
array.astype('bool')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [14]:
array[2] = 0
array

array([ 0.11928221,  0.96270531,  0.        , -0.36174703,  0.92503407,
        0.44241508, -0.61289282, -1.63363194,  0.08057173, -1.96363072])

In [15]:
array.astype('bool')

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
array.min()

-1.963630720650217

In [17]:
array.max()

0.9627053070623517

In [18]:
array.argmax()

1

In [19]:
array.argmin()

9

In [20]:
array.mean()

-0.20418940956479908

In [21]:
array.sum()

-2.041894095647991

In [22]:
array.var()

0.8613104979517316

In [23]:
array.std()

0.9280681537213372

In [24]:
np.sum(array)

-2.041894095647991

In [25]:
array

array([ 0.11928221,  0.96270531,  0.        , -0.36174703,  0.92503407,
        0.44241508, -0.61289282, -1.63363194,  0.08057173, -1.96363072])

In [26]:
array.sort()

In [27]:
array

array([-1.96363072, -1.63363194, -0.61289282, -0.36174703,  0.        ,
        0.08057173,  0.11928221,  0.44241508,  0.92503407,  0.96270531])

In [28]:
mtx

array([[ 0.31453409,  1.42728671,  0.0250084 ],
       [-0.15931809, -0.70811228,  0.86123226],
       [ 0.74442808,  0.41159497,  0.58874685]])

In [29]:
mtx.T

array([[ 0.31453409, -0.15931809,  0.74442808],
       [ 1.42728671, -0.70811228,  0.41159497],
       [ 0.0250084 ,  0.86123226,  0.58874685]])

## Máscaras

In [30]:
a = np.array([1, 2, 3, 4])

In [31]:
a[[False, True, False, True]]

array([2, 4])

In [32]:
a >= 3

array([False, False,  True,  True])

In [33]:
a[a >= 3]

array([3, 4])

In [34]:
a[a % 2 == 0]

array([2, 4])

In [35]:
a % 2 == 0

array([False,  True, False,  True])