# Aula 05 - Métodos Importantes e Máscaras em Arrays

1. Métodos Importantes
    - ndim
    - shape
    - dtype
    - astype
    - min
    - max
    - argmin
    - argmax
    - sum
    - mean
    - var
    - std
    - sort
    - T
    - reshape

2. Máscaras

In [2]:
import numpy as np

In [3]:
array = np.random.randn(10)

In [4]:
array

array([ 0.08750322,  0.21183463, -0.53803631, -0.53525066, -0.35165849,
        0.25678342, -0.17898542,  1.64678876,  1.38647428,  0.7402866 ])

In [5]:
mtx = np.random.randn(3, 3)

In [6]:
mtx

array([[-0.16818146,  1.60420931, -0.28131795],
       [-0.60660859, -1.62667801,  1.31636158],
       [ 0.92640001, -0.15887591,  1.39391814]])

In [7]:
array.ndim

1

In [8]:
mtx.ndim

2

In [9]:
array.shape

(10,)

In [10]:
mtx.shape

(3, 3)

In [11]:
array.dtype

dtype('float64')

In [12]:
array.astype('int')

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [13]:
mtx.astype('int')

array([[ 0,  1,  0],
       [ 0, -1,  1],
       [ 0,  0,  1]])

In [14]:
array.astype('bool')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
array[2] = 0
array

array([ 0.08750322,  0.21183463,  0.        , -0.53525066, -0.35165849,
        0.25678342, -0.17898542,  1.64678876,  1.38647428,  0.7402866 ])

In [16]:
array.astype('bool')

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
array.min()

-0.5352506573560943

In [18]:
array.max()

1.6467887634841545

In [19]:
array.argmax()

7

In [20]:
array.argmin()

3

In [21]:
array.mean()

0.3263776334002013

In [22]:
array.sum()

3.263776334002013

In [23]:
array.var()

0.4677685990228955

In [24]:
array.std()

0.6839361074127432

In [25]:
np.sum(array)

3.263776334002013

In [26]:
array

array([ 0.08750322,  0.21183463,  0.        , -0.53525066, -0.35165849,
        0.25678342, -0.17898542,  1.64678876,  1.38647428,  0.7402866 ])

In [27]:
array.sort()

In [28]:
array

array([-0.53525066, -0.35165849, -0.17898542,  0.        ,  0.08750322,
        0.21183463,  0.25678342,  0.7402866 ,  1.38647428,  1.64678876])

In [29]:
mtx

array([[-0.16818146,  1.60420931, -0.28131795],
       [-0.60660859, -1.62667801,  1.31636158],
       [ 0.92640001, -0.15887591,  1.39391814]])

In [30]:
mtx.T

array([[-0.16818146, -0.60660859,  0.92640001],
       [ 1.60420931, -1.62667801, -0.15887591],
       [-0.28131795,  1.31636158,  1.39391814]])

## Máscaras

In [31]:
a = np.array([1, 2, 3, 4])

In [32]:
a[[False, True, False, True]]

array([2, 4])

In [33]:
a >= 3

array([False, False,  True,  True])

In [34]:
a[a >= 3]

array([3, 4])

In [35]:
a[a % 2 == 0]

array([2, 4])

In [36]:
a % 2 == 0

array([False,  True, False,  True])

In [37]:
print(a)

[1 2 3 4]
